name: Build and Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Enable multi-arch builds for Raspberry Pi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ARM64 image to Docker Hub
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/object-detection:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/object-detection:${{ github.sha }} \
            -f app/Dockerfile \
            app/ \
            --push

      # Trigger deploy script on Raspberry Pi (pulls image + blue-green switch)
      - name: Deploy on Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            cd /home/${{ secrets.DEPLOY_USER }}/object-detection-app
            ./deploy.sh ${{ secrets.DOCKERHUB_USERNAME }}/object-detection:latest
